<a href="https://colab.research.google.com/github/aliochilov/Tashkent_house_price/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%2205_ml_05_amaliyot_ipynb%22%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## 5-MODUL. Machine Learning

### Portfolio uchun vazifa: Toshkent shahrida uylarning narxini aniqlash.

Ushbu amaliyotda sizning vazifangiz berilgan ma`lumotlar asosida Toshkent shahridagi uylarning narxini aniqlash.

In [ ]:
import numpy as np
import sklearn
import pandas as pd
import matplotlib.pyplot as plt
URL = "https://github.com/aliochilov/Tashkent_house_price/blob/main/tashkent_house_price.scv?raw=True"
df = pd.read_csv(URL)
df.head()
df  = df.drop('location', axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

X_train = train_set.drop("price", axis=1)
y = train_set["price"].copy()

X_num = X_train.drop("district", axis=1)



In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

num_pipeline = Pipeline([
          ('imputer', SimpleImputer(strategy='median')),
          ('std_scaler', StandardScaler())             
])

In [ ]:
from sklearn.compose import ColumnTransformer

num_attribs = list(X_num)
cat_attribs = ['district']

full_pipeline = ColumnTransformer([
    ('num', num_pipeline, num_attribs),
    ('cat', OneHotEncoder(), cat_attribs)
])

In [ ]:
X_prepared = full_pipeline.fit_transform(X_train)

In [ ]:
X_prepared[0:5,:]

array([[-0.57746118, -0.03810884, -0.31266907, -0.78950544,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 1.25131698,  0.06793077, -0.75864437, -0.40330378,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-1.49185026, -0.04832006, -0.75864437, -0.40330378,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.57746118, -0.02082831, -0.31266907, -0.01710212,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ],
       [ 1.25131698,  0.05065024,  0

In [ ]:
from sklearn.linear_model import LinearRegression

LR_model = LinearRegression()


In [ ]:
LR_model.fit(X_prepared, y)

LinearRegression()

In [ ]:
# tasodifiy 5 ta qatorni ajratib olamiz
test_data = X_train.sample(5)
test_data

district  rooms   size  level  max_levels
1132  Чиланзарский      5  109.0      5           5
5438   Учтепинский      2   48.0      2           4
363   Юнусабадский      2   62.0      4           9
3040  Чиланзарский      2   50.0      2           4
1347   Учтепинский      2   48.0      5           5

In [ ]:
test_label = y.loc[test_data.index]
test_label

1132    83000
5438    40500
363     55000
3040    38500
1347    31000
Name: price, dtype: int64

In [ ]:
test_data_prepared = full_pipeline.transform(test_data)
test_data_prepared

array([[ 2.16570605,  0.00666344,  0.57928154, -0.40330378,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-0.57746118, -0.04125076, -0.75864437, -0.78950544,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-0.57746118, -0.03025406,  0.13330623,  1.14150286,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ],
       [-0.57746118, -0.0396798 , -0.75864437, -0.78950544,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-0.57746118, -0.04125076,  0

In [ ]:
predicted_data = LR_model.predict(test_data_prepared)
predicted_data

array([122629.63722517,  98647.03630008,  53505.70052158,  38927.61876012,
        85207.19603225])

In [ ]:
pd.DataFrame({'Prognoz':predicted_data, 'Real baxosi': test_label})

Prognoz  Real baxosi
1132  122629.637225        83000
5438   98647.036300        40500
363    53505.700522        55000
3040   38927.618760        38500
1347   85207.196032        31000

In [ ]:
X_test = test_set.drop('price', axis=1)
X_test

district  rooms   size  level  max_levels
132        Чиланзарский      2   37.0      1           4
3771       Сергелийский      1   39.0      5           5
65          Учтепинский      4  110.0      3           3
7525    Шайхантахурский      4   84.0      2           4
6791        Мирабадский      4  100.0      3           4
...                 ...    ...    ...    ...         ...
4834       Чиланзарский      2   50.0      2           5
3125  Мирзо-Улугбекский      4   92.0      4           4
347         Яшнободский      2   59.0      4           4
6678       Сергелийский      3   57.0      3           7
333        Чиланзарский      2   58.0      1           9

[1513 rows x 5 columns]

In [ ]:
y_test = test_set['price'].copy()
y_test

132      41000
3771     21000
65       91000
7525     95000
6791     88000
         ...  
4834     36000
3125    130000
347      26500
6678     43000
333      40000
Name: price, Length: 1513, dtype: int64

In [ ]:
X_test_prepared = full_pipeline.transform(X_test)

In [ ]:
y_predicted = LR_model.predict(X_test_prepared)

In [ ]:
from sklearn.metrics import mean_squared_error
lin_mse = mean_squared_error(y_test, y_predicted)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

224707.86087045638


In [ ]:
from sklearn.tree import DecisionTreeRegressor
Tree_model = DecisionTreeRegressor()
Tree_model.fit(X_prepared, y)

DecisionTreeRegressor()

In [ ]:
y_predicted = Tree_model.predict(X_test_prepared)

In [ ]:
lin_mse = mean_squared_error(y_test, y_predicted)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

241465.70227693015


In [ ]:
from sklearn.ensemble import RandomForestRegressor
RF_model = RandomForestRegressor()
RF_model.fit(X_prepared, y)

RandomForestRegressor()

In [ ]:
y_predicted = RF_model.predict(X_test_prepared)
lin_mse = mean_squared_error(y_test, y_predicted)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

578654.2466328348


In [ ]:
X = df.drop("price", axis=1)
y = df["price"].copy()

X_prepared = full_pipeline.transform(X)

In [ ]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Std.dev:", scores.std())

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
scores = cross_val_score(LR_model, X_prepared, y, scoring="neg_mean_squared_error", cv=10)
LR_rmse_scores = np.sqrt(-scores)

In [ ]:
display_scores(LR_rmse_scores)

Scores: [  72326.26936349   46479.05517823  143571.53757696   42656.20992065
   51131.90072745   43278.86819228   51712.71598286 1888809.95554047
  165849.00698201  646007.98672432]
Mean: 315182.3506188715
Std.dev: 552812.9508175949


In [ ]:
scores = cross_val_score(Tree_model, X_prepared, y, scoring="neg_mean_squared_error", cv=10)
LR_rmse_scores = np.sqrt(-scores)
display_scores(LR_rmse_scores)

Scores: [  64133.40857691  287661.96201748  142998.20514461  207481.71337888
  565369.38324304   64085.98692918  287208.78282324 1889079.8894664
  162606.85173118  641372.33005794]
Mean: 431199.85133688536
Std.dev: 519969.92697265826
